### ISSUE TITLE
document.getElementById

### ISSUE THREAD

**Issue by jcugno** [iamnoah/writeCapture#5]
Running into a situation with an ad script doing the following:

var divid='dclkAdsDivID_6302';
document.write('<div id=' + divid + '></div>');
var iframe_6302=document.createElement('iframe');
iframe_6302.id='dclkAdsFrameID_6302';
iframe_6302.name='dclkAdsFrameName_6302';
iframe_6302.src="about:blank";
iframe_6302.scrolling="no";
iframe_6302.width=728;
iframe_6302.height=90;
iframe_6302.frameborder=0;
iframe_6302.style.border=0;
iframe_6302.allowtransparency="true";
iframe_6302.hspace=0;
iframe_6302.vspace=0;
iframe_6302.marginHeight=0;
iframe_6302.marginWidth=0;
var parent_6302 = document.getElementById(divid);
parent_6302.appendChild(iframe_6302);

The problem is that  document.getElementById on the new div that was just placed with document.write (and is just part of state.out) is going to return undefined since the DOM doesn't have this new div yet.

Wondering what your thoughts on this are?

**Comment by iamnoah** [comment]
It's like this script was created just to spite you. The author clearly knows that you can create elements dynamically and append them, which he does for the most part, but instead of a document.body.append, a document.write is thrown in, just to f- with you.

I'll see if there is something writeCapture can do, but this is on the short list of cases that is probably impossible to cover. In this particular case, you could just replace document.write with a noop and put your own div in the document (so it's already there), but that's not exactly future proof.

**Comment by iamnoah** [comment]
So I think we could implement a hack around document.getElementById that returns a temporary element for it to append to, and then move the content to the real element afterwards... but it wouldn't always work. If document.write was used to add content to the real element after the append supposedly happened (which may not be possible, but I'm not sure), then the appended content would end up after that, which would be wrong. e.g.,

```
document.write('<div id=myDiv>');
document.getElementById('myDiv').appendChild(iframe);
document.write('Something after the iframe</div>');
```

You would end up with:

```
<div id="myDiv">Something after the iframe<iframe .../></div>
```

Or worse, "Something after the iframe" should be outside the div because grabbing it with getElementById closes it.

**Comment by iamnoah** [comment]
I've added a hack that I think might help your case. Try the latest master and add a line somewhere before you use writeCapture that looks like one of these:

```
 writeCapture.proxyGetElementById = true;
 // or for the jQuery plugin:
 jQuery.writeCapture.proxyGetElementById = true;
```

**Comment by jcugno** [comment]
The scripts keep getting worse and worse, now I see this coming back:

parent_31003.appendChild(iframe_31003);
20var iframeDoc_31003 = document.getElementById("dclkAdsFrameID_31003").contentWindow.document;
21iframeDoc_31003.open();
22iframeDoc_31003.write(adsenseHtml_31003);
23window.setTimeout("iframeDoc_31003.close();", 2000);

.contentWindow is undefined ;)

The people who write the ad scripts are just horrible!

**Comment by iamnoah** [comment]
Eww yea, there really isn't anything we can do about that because it involves native objects. That script will only work on page load, sorry.

**Comment by jcugno** [comment]
Ok bleh, thanks for the help though. Appreciate it!

**Comment by jcugno** [comment]
What are your thoughts on something like this? I think it's working:

function makeTemp(id) {
            var t = global.document.createElement('div');
            t.contentWindow = {document : {open : function(){}, html : '', write : function(str){this.html = str;}, close : function(){}}};
            state.tempEls.push({id:id,el:t});
            return t;
        }

and then for the appending:
finish: function() {
                each(this.tempEls,function(it) {

```
                var tempHTML = '';
                if (it.el.contentWindow !== undefined && it.el.contentWindow.document !== undefined && it.el.contentWindow.document.html !== '') {
                    tempHTML = it.el.contentWindow.document.html;
                    var test = document.getElementById(it.id);
                    test.contentWindow.document.open();
                    test.contentWindow.document.write(tempHTML);
                    window.setTimeout(function(){test.contentWindow.document.close();}, 2000);
                }
                var real = document.getElementById(it.id);
                each(it.el.childNodes,function(it) { 
                    real.appendChild(it);
                });
            });
        },
```

**Comment by iamnoah** [comment]
That's pretty specific... I'm not sure how far mocking it like that will get us, but let me play with this a little bit.

**Comment by iamnoah** [comment]
Support for mocking contentWindow has been added and it seems to work. Check out the latest master.
