### ISSUE TITLE
StatCounter tracking tag failing in IE 6, 7 and 8.

### ISSUE THREAD

**Issue by jasper-ferrer** [iamnoah/writeCapture#9]
There is no Javascript error but a message (generated by the tag) that says: "Code corrupted. Insert fresh copy."

Here's the code:

```
$.writeCapture.proxyGetElementById = true;

$("#placeHolder1").writeCapture(
    "html", 
    "<!-- Start of StatCounter Code --><script type=\"text/javascript\">\n" +
    "var sc_project=5545436; \n" +
    "var sc_invisible=1; \n" +
    "var sc_security=\"823496b7\"; \n" +
    "</script><script type=\"text/javascript\" src=\"http://www.statcounter.com/counter/counter.js\"></script><!-- End of StatCounter Code -->\n" );
```

**Comment by iamnoah** [comment]
Hi Jasper,

Two things:
1. Try the latest code, but instead of setting proxyGetElementById = true, set writeOnGetElementById = true. That strategy sometimes works better.
2. Based on the counter code, it appears to expect a global var named usr to be set:    
   
   if(window.usr){sc_base_dir+="usr="+usr}else{sc_error=1}

Make sure you have that variable set before loading the script.

**Comment by iamnoah** [comment]
Closing because I don't think this is writeCapture related. Please open a new ticket if you find an issue with writeCapture. Thanks!
